### ISSUE TITLE
Bug: Python build fails: NameError: name 'compile_args' is not defined

### ISSUE THREAD

**Issue by yurivict** [ashvardanian/StringZilla#187]
### Describe the bug

```
===>  Configuring for py311-stringzilla-3.10.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 138, in <module>
    extra_compile_args=compile_args,
                       ^^^^^^^^^^^^
NameError: name 'compile_args' is not defined
*** Error code 1
```

py311-setuptools-63.1.0
FreeBSD 14.1

### Steps to reproduce

n/a

### Expected behavior

n/a

### StringZilla version

3.10.6

### Operating System

FreeBSD 14.1

### Hardware architecture

x86

### Which interface are you using?

C implementation

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
I am glad someone has opened this issue, @yurivict! Thanks a lot!

```py
if sys.platform == "linux":
    compile_args, link_args, macros_args = linux_settings()

elif sys.platform == "darwin":
    compile_args, link_args, macros_args = darwin_settings()

elif sys.platform == "win32":
    compile_args, link_args, macros_args = windows_settings()

# TODO: It would be great to infer available compilation flags on FreeBSD. They are likely similar to Linux
else:
    compile_args, link_args, macros_args = [], [], []
```

I'm submitting a hot-patch - it will only take a couple of lines of code, but I would love to ask for your help as you must be intimately familiar with the FreeBSD ecosystem! I believe GCC/Clang should be the compilers of choice on FreeBSD as well. Can you please check if the following flags make sense for FreeBSD builds?

```py
    compile_args.append("-std=c11")
    compile_args.append("-O3")
    compile_args.append("-ffast-math")
    compile_args.append("-fdiagnostics-color=always")
    compile_args.append("-fvisibility=default")
    compile_args.append("-fPIC")
    link_args.append("-shared")

    # Disable warnings
    compile_args.append("-w")

    # Enable OpenMP for Linux
    compile_args.append("-fopenmp")
    link_args.append("-fopenmp")

    # Add vectorized `logf` implementation from the `glibc`
    link_args.append("-lm")

    # SIMD all the way on Linux!
    macros_args.extend(
        [
            get_bool_env_w_name("SIMSIMD_TARGET_NEON", True),
            get_bool_env_w_name("SIMSIMD_TARGET_NEON_F16", True),
            get_bool_env_w_name("SIMSIMD_TARGET_NEON_BF16", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SVE", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SVE_F16", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SVE_BF16", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SVE2", True),
            get_bool_env_w_name("SIMSIMD_TARGET_HASWELL", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SKYLAKE", True),
            get_bool_env_w_name("SIMSIMD_TARGET_ICE", True),
            get_bool_env_w_name("SIMSIMD_TARGET_GENOA", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SAPPHIRE", True),
            get_bool_env_w_name("SIMSIMD_TARGET_TURIN", True),
            get_bool_env_w_name("SIMSIMD_TARGET_SIERRA", False),  # TODO: Add target spec to GCC & Clang
        ]
    )
```

We also should add a pre-release test pipeline that would emulate FreeBSD and ensure we don't break compatibility in the future.

Your help would not only affect StringZilla, but also [SimSIMD](https://github.com/ashvardanian/simsimd), and [USearch](https://github.com/unum-cloud/usearch), and huge portion of search systems worldwide.

**Comment by yurivict** [comment]
Hi @ashvardanian ,

The following script worked for me:
```
--- setup.py.orig   2024-12-19 07:27:15 UTC
+++ setup.py
@@ -118,7 +118,7 @@ def windows_settings() -> Tuple[List[str], List[str], 
     return compile_args, link_args, macros_args


-if sys.platform == "linux":
+if sys.platform == "linux" or sys.platform.startswith('freebsd'):
     compile_args, link_args, macros_args = linux_settings()

 elif sys.platform == "darwin":
```

FreeBSD's toolchains are very similar to Linux toolchains.

Ideally compiler options should be based on the compiler that is used, not on OS.

But in this case the options mostly fit both gcc and clang compilers.

Please see these warnings for one exception:
```
cc -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -DSZ_DYNAMIC_DISPATCH=1 -DSZ_USE_X86_AVX512=0 -DSZ_USE_X86_AVX2=0 -DSZ_USE_ARM_SVE=0 -DSZ_USE_ARM_NEON=0 -DSZ_DETECT_BIG_ENDIAN=0 -Iinclude -I/usr/local/include/python3.11 -c c/lib.c -o build/temp.freebsd-14.2-STABLE-amd64-cpython-311/c/lib.o -std=c99 -pedantic -O3 -fdiagnostics-color=always -Wno-unknown-pragmas -Wno-unused-function -Wno-incompatible-pointer-types -Wno-discarded-qualifiers -fPIC
warning: unknown warning option '-Wno-discarded-qualifiers'; did you mean '-Wno-ignored-qualifiers'? [-Wunknown-warning-option]
1 warning generated.
cc -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -DSZ_DYNAMIC_DISPATCH=1 -DSZ_USE_X86_AVX512=0 -DSZ_USE_X86_AVX2=0 -DSZ_USE_ARM_SVE=0 -DSZ_USE_ARM_NEON=0 -DSZ_DETECT_BIG_ENDIAN=0 -Iinclude -I/usr/local/include/python3.11 -c python/lib.c -o build/temp.freebsd-14.2-STABLE-amd64-cpython-311/python/lib.o -std=c99 -pedantic -O3 -fdiagnostics-color=always -Wno-unknown-pragmas -Wno-unused-function -Wno-incompatible-pointer-types -Wno-discarded-qualifiers -fPIC
warning: unknown warning option '-Wno-discarded-qualifiers'; did you mean '-Wno-ignored-qualifiers'? [-Wunknown-warning-option]
python/lib.c:3342:30: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
 3342 |     for (Py_ssize_t i = 0; i < sample_size; i++) {
      |                            ~ ^ ~~~~~~~~~~~
2 warnings generated.
```

**Comment by ashvardanian** [comment]
Thanks, @yurivict! Can you open a PR for that platform checking line?

**Comment by yurivict** [comment]
https://github.com/ashvardanian/StringZilla/pull/205

**Comment by ashvardanian** [comment]
Thank you, @yurivict 🤗
